Mats:
  - Type: 1
    Glow:
      - 0
      - 0
      - 0
    Albedo:
      - 0.800000012
      - 0.200000003
      - 0.100000001
  - Type: 1
    Glow:
      - 0
      - 0
      - 0
    Albedo:
      - 0.100000012
      - 0.800000003
      - 0.200000001
World:
  Camera:
    Pos:
      - 0
      - 0
      - 0
    Front:
      - 1
      - 0
      - 0
    Up:
      - 0
      - 1
      - 0
    Hor: 1.57000005
    Perp: 1.57000005
  Background:
    - 1
    - 1
    - 1
  Geos:
    - Type: 2
      Material: 0
      Center:
        - 1
        - 0.200000001
        - 0
      Radius: 0.200000001
    - Type: 1
      Material: 1
      Vertices:
        -
          - -0.100000001
          - -0.0500000007
          - -5
        -
          - -0.100000001
          - -0.0500000007
          - 5
        -
          - 5
          - -0.0500000007
          - -5
      Norm:
        - 0
        - 1
        - 0
    - Type: 1
      Material: 1
      Vertices:
        -
          - -0.100000001
          - -0.0500000007
          - 5
        -
          - 5
          - -0.0500000007
          - 5
        -
          - 5
          - -0.0500000007
          - -5
      Norm:
        - -0
        - 1
        - 0
Image:
  Width: 512
  Height: 256
  Channels: 3
  Filepath: ""