world:
  Camera:
    Pos:
      - 0
      - 0
      - 0
    Front:
      - 1
      - 0
      - 0
    Up:
      - 0
      - 1
      - 0
    Hor: 1.5
    Perp: 1.03999996
  Background:
    - 1
    - 1
    - 1
  Geos:
    - Type: 2
      Material:
        Type: 3
        Glow:
          - 0
          - 0
          - 0
        Ir: 1.5
      Center:
        - 1
        - 0
        - -0.360000014
      Radius: 0.349999994
    - Type: 2
      Material:
        Type: 2
        Glow:
          - 0
          - 0
          - 0
        Albedo:
          - 0.800000012
          - 0.200000003
          - 0.100000001
        Fuzz: 0
      Center:
        - 3
        - -0.200000003
        - 0
      Radius: 0.150000006
    - Type: 2
      Material:
        Type: 2
        Glow:
          - 0
          - 0
          - 0
        Albedo:
          - 0.800000012
          - 0.100000001
          - 0.200000003
        Fuzz: 0.100000001
      Center:
        - 1
        - 0
        - 0.360000014
      Radius: 0.349999994
    - Type: 1
      Material:
        Type: 1
        Glow:
          - 0
          - 0
          - 0
        Albedo:
          - 0.100000001
          - 0.200000003
          - 0.800000012
      Vertices:
        -
          - -18
          - -0.349999994
          - -3
        -
          - 18
          - -0.349999994
          - 3
        -
          - 18
          - -0.349999994
          - -3
      Norm:
        - 0
        - 1
        - 0
    - Type: 1
      Material:
        Type: 1
        Glow:
          - 0
          - 0
          - 0
        Albedo:
          - 0.100000001
          - 0.200000003
          - 0.800000012
      Vertices:
        -
          - -18
          - -0.349999994
          - -3
        -
          - -18
          - -0.349999994
          - 3
        -
          - 18
          - -0.349999994
          - 3
      Norm:
        - 0
        - 1
        - 0